### ISSUE TITLE
Examples have additionnal dependencies required

### ISSUE THREAD

**Issue by alexpron** [gauzias/slam#21]
When running slam examples, additionnal packages are required (pyglet, rtree, shapely), examples should either be reformatted or dependencies included in the install process

**Comment by MaximeDdnn** [comment]
(1) "no module named pyglet"  : example_generate_parametric_surfaces.py , example_mapping.py   
(2)" no module named shapely" : example_geodesic.py   
(3) "no module named rtree" : example_registrations.py .

**Comment by gauzias** [comment]
that is because 'examples' in the 'example' folder are old ones that are no longer necessary.
This folder should be deleted and all examples are now supposed to be located in my_examples

**Comment by alexpron** [comment]
Nice, that eases the pull request :) should the my-examples folder be renamed 'examples' ?

**Comment by gauzias** [comment]
not yet because 'my_examples' is the one that is used to generate the github pages, i.e. the doc website
So we should change the name properly.
Let's do it in two steps, first deleting the 'examples' folder

**Comment by alexpron** [comment]
Perfect I assign both @MaximeDdnn and @alexpron so that we can try the pull request process in this simple case

**Comment by gauzias** [comment]
mes_examples have been deleted
